import { z } from 'zod';
export declare const featuredProductItemSchema: z.ZodObject<{
    id: z.ZodString;
    tenantId: z.ZodString;
    productId: z.ZodString;
    sortOrder: z.ZodNumber;
    createdAt: z.ZodString;
    product: z.ZodObject<{
        id: z.ZodString;
        tenantId: z.ZodString;
        identityRank: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        alias: z.ZodNullable<z.ZodString>;
        code: z.ZodNullable<z.ZodString>;
        type: z.ZodEnum<["breeder", "offspring"]>;
        lineageType: z.ZodEnum<["pure", "hybrid"]>;
        crossLabel: z.ZodNullable<z.ZodString>;
        name: z.ZodNullable<z.ZodString>;
        description: z.ZodNullable<z.ZodString>;
        seriesId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        sex: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        sireProductId: z.ZodNullable<z.ZodString>;
        damProductId: z.ZodNullable<z.ZodString>;
        mateProductId: z.ZodNullable<z.ZodString>;
        requiresIdentityReview: z.ZodOptional<z.ZodBoolean>;
        needMatingStatus: z.ZodOptional<z.ZodNullable<z.ZodEnum<["normal", "need_mating", "warning"]>>>;
        lastEggAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        lastMatingAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        daysSinceEgg: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        offspringUnitPrice: z.ZodOptional<z.ZodEffects<z.ZodNullable<z.ZodNumber>, number | null, unknown>>;
        excludeFromBreeding: z.ZodOptional<z.ZodBoolean>;
        hasSample: z.ZodOptional<z.ZodBoolean>;
        inStock: z.ZodOptional<z.ZodBoolean>;
        popularityScore: z.ZodOptional<z.ZodNumber>;
        isFeatured: z.ZodOptional<z.ZodBoolean>;
        coverImageUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        createdAt: z.ZodOptional<z.ZodString>;
        updatedAt: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        code: string | null;
        type: "breeder" | "offspring";
        id: string;
        alias: string | null;
        name: string | null;
        tenantId: string;
        description: string | null;
        lineageType: "pure" | "hybrid";
        crossLabel: string | null;
        sireProductId: string | null;
        damProductId: string | null;
        mateProductId: string | null;
        coverImageUrl?: string | null | undefined;
        sex?: string | null | undefined;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        isFeatured?: boolean | undefined;
        identityRank?: number | null | undefined;
        seriesId?: string | null | undefined;
        requiresIdentityReview?: boolean | undefined;
        needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
        lastEggAt?: string | null | undefined;
        lastMatingAt?: string | null | undefined;
        daysSinceEgg?: number | null | undefined;
        offspringUnitPrice?: number | null | undefined;
        excludeFromBreeding?: boolean | undefined;
        hasSample?: boolean | undefined;
        inStock?: boolean | undefined;
        popularityScore?: number | undefined;
    }, {
        code: string | null;
        type: "breeder" | "offspring";
        id: string;
        alias: string | null;
        name: string | null;
        tenantId: string;
        description: string | null;
        lineageType: "pure" | "hybrid";
        crossLabel: string | null;
        sireProductId: string | null;
        damProductId: string | null;
        mateProductId: string | null;
        coverImageUrl?: string | null | undefined;
        sex?: string | null | undefined;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        isFeatured?: boolean | undefined;
        identityRank?: number | null | undefined;
        seriesId?: string | null | undefined;
        requiresIdentityReview?: boolean | undefined;
        needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
        lastEggAt?: string | null | undefined;
        lastMatingAt?: string | null | undefined;
        daysSinceEgg?: number | null | undefined;
        offspringUnitPrice?: unknown;
        excludeFromBreeding?: boolean | undefined;
        hasSample?: boolean | undefined;
        inStock?: boolean | undefined;
        popularityScore?: number | undefined;
    }>;
}, "strip", z.ZodTypeAny, {
    id: string;
    product: {
        code: string | null;
        type: "breeder" | "offspring";
        id: string;
        alias: string | null;
        name: string | null;
        tenantId: string;
        description: string | null;
        lineageType: "pure" | "hybrid";
        crossLabel: string | null;
        sireProductId: string | null;
        damProductId: string | null;
        mateProductId: string | null;
        coverImageUrl?: string | null | undefined;
        sex?: string | null | undefined;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        isFeatured?: boolean | undefined;
        identityRank?: number | null | undefined;
        seriesId?: string | null | undefined;
        requiresIdentityReview?: boolean | undefined;
        needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
        lastEggAt?: string | null | undefined;
        lastMatingAt?: string | null | undefined;
        daysSinceEgg?: number | null | undefined;
        offspringUnitPrice?: number | null | undefined;
        excludeFromBreeding?: boolean | undefined;
        hasSample?: boolean | undefined;
        inStock?: boolean | undefined;
        popularityScore?: number | undefined;
    };
    tenantId: string;
    createdAt: string;
    sortOrder: number;
    productId: string;
}, {
    id: string;
    product: {
        code: string | null;
        type: "breeder" | "offspring";
        id: string;
        alias: string | null;
        name: string | null;
        tenantId: string;
        description: string | null;
        lineageType: "pure" | "hybrid";
        crossLabel: string | null;
        sireProductId: string | null;
        damProductId: string | null;
        mateProductId: string | null;
        coverImageUrl?: string | null | undefined;
        sex?: string | null | undefined;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        isFeatured?: boolean | undefined;
        identityRank?: number | null | undefined;
        seriesId?: string | null | undefined;
        requiresIdentityReview?: boolean | undefined;
        needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
        lastEggAt?: string | null | undefined;
        lastMatingAt?: string | null | undefined;
        daysSinceEgg?: number | null | undefined;
        offspringUnitPrice?: unknown;
        excludeFromBreeding?: boolean | undefined;
        hasSample?: boolean | undefined;
        inStock?: boolean | undefined;
        popularityScore?: number | undefined;
    };
    tenantId: string;
    createdAt: string;
    sortOrder: number;
    productId: string;
}>;
export declare const listFeaturedProductsResponseSchema: z.ZodObject<{
    items: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        tenantId: z.ZodString;
        productId: z.ZodString;
        sortOrder: z.ZodNumber;
        createdAt: z.ZodString;
        product: z.ZodObject<{
            id: z.ZodString;
            tenantId: z.ZodString;
            identityRank: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            alias: z.ZodNullable<z.ZodString>;
            code: z.ZodNullable<z.ZodString>;
            type: z.ZodEnum<["breeder", "offspring"]>;
            lineageType: z.ZodEnum<["pure", "hybrid"]>;
            crossLabel: z.ZodNullable<z.ZodString>;
            name: z.ZodNullable<z.ZodString>;
            description: z.ZodNullable<z.ZodString>;
            seriesId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            sex: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            sireProductId: z.ZodNullable<z.ZodString>;
            damProductId: z.ZodNullable<z.ZodString>;
            mateProductId: z.ZodNullable<z.ZodString>;
            requiresIdentityReview: z.ZodOptional<z.ZodBoolean>;
            needMatingStatus: z.ZodOptional<z.ZodNullable<z.ZodEnum<["normal", "need_mating", "warning"]>>>;
            lastEggAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            lastMatingAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            daysSinceEgg: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            offspringUnitPrice: z.ZodOptional<z.ZodEffects<z.ZodNullable<z.ZodNumber>, number | null, unknown>>;
            excludeFromBreeding: z.ZodOptional<z.ZodBoolean>;
            hasSample: z.ZodOptional<z.ZodBoolean>;
            inStock: z.ZodOptional<z.ZodBoolean>;
            popularityScore: z.ZodOptional<z.ZodNumber>;
            isFeatured: z.ZodOptional<z.ZodBoolean>;
            coverImageUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            createdAt: z.ZodOptional<z.ZodString>;
            updatedAt: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        }, {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        }>;
    }, "strip", z.ZodTypeAny, {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }, {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    items: {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }[];
}, {
    items: {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }[];
}>;
export declare const createFeaturedProductRequestSchema: z.ZodObject<{
    productId: z.ZodString;
    sortOrder: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    productId: string;
    sortOrder?: number | undefined;
}, {
    productId: string;
    sortOrder?: number | undefined;
}>;
export declare const createFeaturedProductResponseSchema: z.ZodObject<{
    item: z.ZodObject<{
        id: z.ZodString;
        tenantId: z.ZodString;
        productId: z.ZodString;
        sortOrder: z.ZodNumber;
        createdAt: z.ZodString;
        product: z.ZodObject<{
            id: z.ZodString;
            tenantId: z.ZodString;
            identityRank: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            alias: z.ZodNullable<z.ZodString>;
            code: z.ZodNullable<z.ZodString>;
            type: z.ZodEnum<["breeder", "offspring"]>;
            lineageType: z.ZodEnum<["pure", "hybrid"]>;
            crossLabel: z.ZodNullable<z.ZodString>;
            name: z.ZodNullable<z.ZodString>;
            description: z.ZodNullable<z.ZodString>;
            seriesId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            sex: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            sireProductId: z.ZodNullable<z.ZodString>;
            damProductId: z.ZodNullable<z.ZodString>;
            mateProductId: z.ZodNullable<z.ZodString>;
            requiresIdentityReview: z.ZodOptional<z.ZodBoolean>;
            needMatingStatus: z.ZodOptional<z.ZodNullable<z.ZodEnum<["normal", "need_mating", "warning"]>>>;
            lastEggAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            lastMatingAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            daysSinceEgg: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            offspringUnitPrice: z.ZodOptional<z.ZodEffects<z.ZodNullable<z.ZodNumber>, number | null, unknown>>;
            excludeFromBreeding: z.ZodOptional<z.ZodBoolean>;
            hasSample: z.ZodOptional<z.ZodBoolean>;
            inStock: z.ZodOptional<z.ZodBoolean>;
            popularityScore: z.ZodOptional<z.ZodNumber>;
            isFeatured: z.ZodOptional<z.ZodBoolean>;
            coverImageUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            createdAt: z.ZodOptional<z.ZodString>;
            updatedAt: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        }, {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        }>;
    }, "strip", z.ZodTypeAny, {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }, {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }>;
}, "strip", z.ZodTypeAny, {
    item: {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    };
}, {
    item: {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    };
}>;
export declare const deleteFeaturedProductResponseSchema: z.ZodObject<{
    deleted: z.ZodLiteral<true>;
    id: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    deleted: true;
}, {
    id: string;
    deleted: true;
}>;
export declare const reorderFeaturedProductsRequestSchema: z.ZodEffects<z.ZodObject<{
    ids: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    productIds: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    ids?: string[] | undefined;
    productIds?: string[] | undefined;
}, {
    ids?: string[] | undefined;
    productIds?: string[] | undefined;
}>, {
    ids?: string[] | undefined;
    productIds?: string[] | undefined;
}, {
    ids?: string[] | undefined;
    productIds?: string[] | undefined;
}>;
export declare const reorderFeaturedProductsResponseSchema: z.ZodObject<{
    items: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        tenantId: z.ZodString;
        productId: z.ZodString;
        sortOrder: z.ZodNumber;
        createdAt: z.ZodString;
        product: z.ZodObject<{
            id: z.ZodString;
            tenantId: z.ZodString;
            identityRank: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            alias: z.ZodNullable<z.ZodString>;
            code: z.ZodNullable<z.ZodString>;
            type: z.ZodEnum<["breeder", "offspring"]>;
            lineageType: z.ZodEnum<["pure", "hybrid"]>;
            crossLabel: z.ZodNullable<z.ZodString>;
            name: z.ZodNullable<z.ZodString>;
            description: z.ZodNullable<z.ZodString>;
            seriesId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            sex: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            sireProductId: z.ZodNullable<z.ZodString>;
            damProductId: z.ZodNullable<z.ZodString>;
            mateProductId: z.ZodNullable<z.ZodString>;
            requiresIdentityReview: z.ZodOptional<z.ZodBoolean>;
            needMatingStatus: z.ZodOptional<z.ZodNullable<z.ZodEnum<["normal", "need_mating", "warning"]>>>;
            lastEggAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            lastMatingAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            daysSinceEgg: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            offspringUnitPrice: z.ZodOptional<z.ZodEffects<z.ZodNullable<z.ZodNumber>, number | null, unknown>>;
            excludeFromBreeding: z.ZodOptional<z.ZodBoolean>;
            hasSample: z.ZodOptional<z.ZodBoolean>;
            inStock: z.ZodOptional<z.ZodBoolean>;
            popularityScore: z.ZodOptional<z.ZodNumber>;
            isFeatured: z.ZodOptional<z.ZodBoolean>;
            coverImageUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            createdAt: z.ZodOptional<z.ZodString>;
            updatedAt: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        }, {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        }>;
    }, "strip", z.ZodTypeAny, {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }, {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    items: {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: number | null | undefined;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }[];
}, {
    items: {
        id: string;
        product: {
            code: string | null;
            type: "breeder" | "offspring";
            id: string;
            alias: string | null;
            name: string | null;
            tenantId: string;
            description: string | null;
            lineageType: "pure" | "hybrid";
            crossLabel: string | null;
            sireProductId: string | null;
            damProductId: string | null;
            mateProductId: string | null;
            coverImageUrl?: string | null | undefined;
            sex?: string | null | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            isFeatured?: boolean | undefined;
            identityRank?: number | null | undefined;
            seriesId?: string | null | undefined;
            requiresIdentityReview?: boolean | undefined;
            needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
            lastEggAt?: string | null | undefined;
            lastMatingAt?: string | null | undefined;
            daysSinceEgg?: number | null | undefined;
            offspringUnitPrice?: unknown;
            excludeFromBreeding?: boolean | undefined;
            hasSample?: boolean | undefined;
            inStock?: boolean | undefined;
            popularityScore?: number | undefined;
        };
        tenantId: string;
        createdAt: string;
        sortOrder: number;
        productId: string;
    }[];
}>;
export declare const listPublicFeaturedProductsQuerySchema: z.ZodObject<{
    limit: z.ZodDefault<z.ZodNumber>;
    tenantId: z.ZodOptional<z.ZodString>;
    tenantSlug: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    tenantId?: string | undefined;
    tenantSlug?: string | undefined;
}, {
    tenantId?: string | undefined;
    tenantSlug?: string | undefined;
    limit?: number | undefined;
}>;
export declare const listPublicFeaturedProductsResponseSchema: z.ZodObject<{
    products: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        tenantId: z.ZodString;
        identityRank: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        alias: z.ZodNullable<z.ZodString>;
        code: z.ZodNullable<z.ZodString>;
        type: z.ZodEnum<["breeder", "offspring"]>;
        lineageType: z.ZodEnum<["pure", "hybrid"]>;
        crossLabel: z.ZodNullable<z.ZodString>;
        name: z.ZodNullable<z.ZodString>;
        description: z.ZodNullable<z.ZodString>;
        seriesId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        sex: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        sireProductId: z.ZodNullable<z.ZodString>;
        damProductId: z.ZodNullable<z.ZodString>;
        mateProductId: z.ZodNullable<z.ZodString>;
        requiresIdentityReview: z.ZodOptional<z.ZodBoolean>;
        needMatingStatus: z.ZodOptional<z.ZodNullable<z.ZodEnum<["normal", "need_mating", "warning"]>>>;
        lastEggAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        lastMatingAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        daysSinceEgg: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        offspringUnitPrice: z.ZodOptional<z.ZodEffects<z.ZodNullable<z.ZodNumber>, number | null, unknown>>;
        excludeFromBreeding: z.ZodOptional<z.ZodBoolean>;
        hasSample: z.ZodOptional<z.ZodBoolean>;
        inStock: z.ZodOptional<z.ZodBoolean>;
        popularityScore: z.ZodOptional<z.ZodNumber>;
        isFeatured: z.ZodOptional<z.ZodBoolean>;
        coverImageUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        createdAt: z.ZodOptional<z.ZodString>;
        updatedAt: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        code: string | null;
        type: "breeder" | "offspring";
        id: string;
        alias: string | null;
        name: string | null;
        tenantId: string;
        description: string | null;
        lineageType: "pure" | "hybrid";
        crossLabel: string | null;
        sireProductId: string | null;
        damProductId: string | null;
        mateProductId: string | null;
        coverImageUrl?: string | null | undefined;
        sex?: string | null | undefined;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        isFeatured?: boolean | undefined;
        identityRank?: number | null | undefined;
        seriesId?: string | null | undefined;
        requiresIdentityReview?: boolean | undefined;
        needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
        lastEggAt?: string | null | undefined;
        lastMatingAt?: string | null | undefined;
        daysSinceEgg?: number | null | undefined;
        offspringUnitPrice?: number | null | undefined;
        excludeFromBreeding?: boolean | undefined;
        hasSample?: boolean | undefined;
        inStock?: boolean | undefined;
        popularityScore?: number | undefined;
    }, {
        code: string | null;
        type: "breeder" | "offspring";
        id: string;
        alias: string | null;
        name: string | null;
        tenantId: string;
        description: string | null;
        lineageType: "pure" | "hybrid";
        crossLabel: string | null;
        sireProductId: string | null;
        damProductId: string | null;
        mateProductId: string | null;
        coverImageUrl?: string | null | undefined;
        sex?: string | null | undefined;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        isFeatured?: boolean | undefined;
        identityRank?: number | null | undefined;
        seriesId?: string | null | undefined;
        requiresIdentityReview?: boolean | undefined;
        needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
        lastEggAt?: string | null | undefined;
        lastMatingAt?: string | null | undefined;
        daysSinceEgg?: number | null | undefined;
        offspringUnitPrice?: unknown;
        excludeFromBreeding?: boolean | undefined;
        hasSample?: boolean | undefined;
        inStock?: boolean | undefined;
        popularityScore?: number | undefined;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    products: {
        code: string | null;
        type: "breeder" | "offspring";
        id: string;
        alias: string | null;
        name: string | null;
        tenantId: string;
        description: string | null;
        lineageType: "pure" | "hybrid";
        crossLabel: string | null;
        sireProductId: string | null;
        damProductId: string | null;
        mateProductId: string | null;
        coverImageUrl?: string | null | undefined;
        sex?: string | null | undefined;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        isFeatured?: boolean | undefined;
        identityRank?: number | null | undefined;
        seriesId?: string | null | undefined;
        requiresIdentityReview?: boolean | undefined;
        needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
        lastEggAt?: string | null | undefined;
        lastMatingAt?: string | null | undefined;
        daysSinceEgg?: number | null | undefined;
        offspringUnitPrice?: number | null | undefined;
        excludeFromBreeding?: boolean | undefined;
        hasSample?: boolean | undefined;
        inStock?: boolean | undefined;
        popularityScore?: number | undefined;
    }[];
}, {
    products: {
        code: string | null;
        type: "breeder" | "offspring";
        id: string;
        alias: string | null;
        name: string | null;
        tenantId: string;
        description: string | null;
        lineageType: "pure" | "hybrid";
        crossLabel: string | null;
        sireProductId: string | null;
        damProductId: string | null;
        mateProductId: string | null;
        coverImageUrl?: string | null | undefined;
        sex?: string | null | undefined;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        isFeatured?: boolean | undefined;
        identityRank?: number | null | undefined;
        seriesId?: string | null | undefined;
        requiresIdentityReview?: boolean | undefined;
        needMatingStatus?: "warning" | "normal" | "need_mating" | null | undefined;
        lastEggAt?: string | null | undefined;
        lastMatingAt?: string | null | undefined;
        daysSinceEgg?: number | null | undefined;
        offspringUnitPrice?: unknown;
        excludeFromBreeding?: boolean | undefined;
        hasSample?: boolean | undefined;
        inStock?: boolean | undefined;
        popularityScore?: number | undefined;
    }[];
}>;
export type FeaturedProductItem = z.infer<typeof featuredProductItemSchema>;
export type CreateFeaturedProductRequest = z.infer<typeof createFeaturedProductRequestSchema>;
export type ReorderFeaturedProductsRequest = z.infer<typeof reorderFeaturedProductsRequestSchema>;
export type ListPublicFeaturedProductsQuery = z.infer<typeof listPublicFeaturedProductsQuerySchema>;
