import { z } from 'zod';
export declare const guiquanLedgerMonthKeySchema: z.ZodString;
export declare const guiquanLedgerBatchStatusSchema: z.ZodEnum<["OPEN", "PARTIAL", "SOLD", "CLOSED"]>;
export declare const guiquanLedgerEntryDirectionSchema: z.ZodEnum<["INCOME", "EXPENSE"]>;
export declare const guiquanLedgerEntryKindSchema: z.ZodEnum<["SALE_TURTLE", "SALE_OFFSPRING", "MANUAL_INCOME", "MANUAL_EXPENSE"]>;
export declare const guiquanLedgerEntrySourceSchema: z.ZodEnum<["SALE_ALLOCATION", "LEDGER_ENTRY"]>;
export declare const guiquanLedgerQuickEntryKindSchema: z.ZodEnum<["SALE_TURTLE", "SALE_OFFSPRING_BATCH", "SALE_OFFSPRING_MANUAL", "MANUAL_INCOME", "MANUAL_EXPENSE"]>;
export declare const guiquanLedgerSummarySchema: z.ZodObject<{
    monthKey: z.ZodString;
    allocationCount: z.ZodNumber;
    soldQuantity: z.ZodNumber;
    realizedRevenue: z.ZodNumber;
    incomeAmount: z.ZodNumber;
    expenseAmount: z.ZodNumber;
    netAmount: z.ZodNumber;
    ledgerEntryCount: z.ZodNumber;
    activeBatchCount: z.ZodNumber;
    remainingQuantity: z.ZodNumber;
    eggsEventCount30d: z.ZodNumber;
    matingsEventCount30d: z.ZodNumber;
    allocationsMissingPriceCount: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    monthKey: string;
    allocationCount: number;
    soldQuantity: number;
    realizedRevenue: number;
    incomeAmount: number;
    expenseAmount: number;
    netAmount: number;
    ledgerEntryCount: number;
    activeBatchCount: number;
    remainingQuantity: number;
    eggsEventCount30d: number;
    matingsEventCount30d: number;
    allocationsMissingPriceCount: number;
}, {
    monthKey: string;
    allocationCount: number;
    soldQuantity: number;
    realizedRevenue: number;
    incomeAmount: number;
    expenseAmount: number;
    netAmount: number;
    ledgerEntryCount: number;
    activeBatchCount: number;
    remainingQuantity: number;
    eggsEventCount30d: number;
    matingsEventCount30d: number;
    allocationsMissingPriceCount: number;
}>;
export declare const guiquanLedgerAllocationItemSchema: z.ZodObject<{
    id: z.ZodString;
    batchNo: z.ZodString;
    femaleProductId: z.ZodString;
    femaleCode: z.ZodString;
    coverImageUrl: z.ZodNullable<z.ZodString>;
    quantity: z.ZodNumber;
    unitPrice: z.ZodNullable<z.ZodNumber>;
    amount: z.ZodNullable<z.ZodNumber>;
    buyerName: z.ZodNullable<z.ZodString>;
    channel: z.ZodNullable<z.ZodString>;
    soldAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    batchNo: string;
    femaleProductId: string;
    femaleCode: string;
    coverImageUrl: string | null;
    quantity: number;
    unitPrice: number | null;
    amount: number | null;
    buyerName: string | null;
    channel: string | null;
    soldAt: string;
}, {
    id: string;
    batchNo: string;
    femaleProductId: string;
    femaleCode: string;
    coverImageUrl: string | null;
    quantity: number;
    unitPrice: number | null;
    amount: number | null;
    buyerName: string | null;
    channel: string | null;
    soldAt: string;
}>;
export declare const guiquanLedgerBatchItemSchema: z.ZodObject<{
    id: z.ZodString;
    femaleProductId: z.ZodString;
    batchNo: z.ZodString;
    femaleCode: z.ZodString;
    coverImageUrl: z.ZodNullable<z.ZodString>;
    status: z.ZodEnum<["OPEN", "PARTIAL", "SOLD", "CLOSED"]>;
    plannedQuantity: z.ZodNumber;
    soldQuantity: z.ZodNumber;
    remainingQuantity: z.ZodNumber;
    priceLow: z.ZodNullable<z.ZodNumber>;
    priceHigh: z.ZodNullable<z.ZodNumber>;
    eventDateSnapshot: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "OPEN" | "PARTIAL" | "SOLD" | "CLOSED";
    soldQuantity: number;
    remainingQuantity: number;
    id: string;
    batchNo: string;
    femaleProductId: string;
    femaleCode: string;
    coverImageUrl: string | null;
    plannedQuantity: number;
    priceLow: number | null;
    priceHigh: number | null;
    eventDateSnapshot: string;
}, {
    status: "OPEN" | "PARTIAL" | "SOLD" | "CLOSED";
    soldQuantity: number;
    remainingQuantity: number;
    id: string;
    batchNo: string;
    femaleProductId: string;
    femaleCode: string;
    coverImageUrl: string | null;
    plannedQuantity: number;
    priceLow: number | null;
    priceHigh: number | null;
    eventDateSnapshot: string;
}>;
export declare const guiquanLedgerEntryItemSchema: z.ZodObject<{
    id: z.ZodString;
    source: z.ZodEnum<["SALE_ALLOCATION", "LEDGER_ENTRY"]>;
    direction: z.ZodEnum<["INCOME", "EXPENSE"]>;
    kind: z.ZodEnum<["SALE_TURTLE", "SALE_OFFSPRING", "MANUAL_INCOME", "MANUAL_EXPENSE"]>;
    title: z.ZodString;
    subjectProductId: z.ZodNullable<z.ZodString>;
    subjectCode: z.ZodNullable<z.ZodString>;
    coverImageUrl: z.ZodNullable<z.ZodString>;
    quantity: z.ZodNullable<z.ZodNumber>;
    unitPrice: z.ZodNullable<z.ZodNumber>;
    amount: z.ZodNullable<z.ZodNumber>;
    counterpartyName: z.ZodNullable<z.ZodString>;
    note: z.ZodNullable<z.ZodString>;
    occurredAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    coverImageUrl: string | null;
    quantity: number | null;
    unitPrice: number | null;
    amount: number | null;
    source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
    direction: "INCOME" | "EXPENSE";
    kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
    title: string;
    subjectProductId: string | null;
    subjectCode: string | null;
    counterpartyName: string | null;
    note: string | null;
    occurredAt: string;
}, {
    id: string;
    coverImageUrl: string | null;
    quantity: number | null;
    unitPrice: number | null;
    amount: number | null;
    source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
    direction: "INCOME" | "EXPENSE";
    kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
    title: string;
    subjectProductId: string | null;
    subjectCode: string | null;
    counterpartyName: string | null;
    note: string | null;
    occurredAt: string;
}>;
export declare const createGuiquanLedgerEntryRequestSchema: z.ZodEffects<z.ZodDiscriminatedUnion<"kind", [z.ZodObject<{
    kind: z.ZodLiteral<"SALE_TURTLE">;
    subjectProductId: z.ZodString;
    amount: z.ZodEffects<z.ZodNumber, number, unknown>;
    counterpartyName: z.ZodOptional<z.ZodString>;
    note: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    amount: number;
    kind: "SALE_TURTLE";
    subjectProductId: string;
    counterpartyName?: string | undefined;
    note?: string | undefined;
}, {
    kind: "SALE_TURTLE";
    subjectProductId: string;
    amount?: unknown;
    counterpartyName?: string | undefined;
    note?: string | undefined;
}>, z.ZodObject<{
    kind: z.ZodLiteral<"SALE_OFFSPRING_BATCH">;
    subjectProductId: z.ZodString;
    saleBatchId: z.ZodString;
    quantity: z.ZodNumber;
    unitPrice: z.ZodEffects<z.ZodNumber, number, unknown>;
    counterpartyName: z.ZodOptional<z.ZodString>;
    note: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    quantity: number;
    unitPrice: number;
    kind: "SALE_OFFSPRING_BATCH";
    subjectProductId: string;
    saleBatchId: string;
    counterpartyName?: string | undefined;
    note?: string | undefined;
}, {
    quantity: number;
    kind: "SALE_OFFSPRING_BATCH";
    subjectProductId: string;
    saleBatchId: string;
    unitPrice?: unknown;
    counterpartyName?: string | undefined;
    note?: string | undefined;
}>, z.ZodObject<{
    kind: z.ZodLiteral<"SALE_OFFSPRING_MANUAL">;
    subjectProductId: z.ZodOptional<z.ZodString>;
    subjectLabel: z.ZodOptional<z.ZodString>;
    quantity: z.ZodOptional<z.ZodNumber>;
    unitPrice: z.ZodOptional<z.ZodEffects<z.ZodNullable<z.ZodNumber>, number | null, unknown>>;
    amount: z.ZodEffects<z.ZodNumber, number, unknown>;
    counterpartyName: z.ZodOptional<z.ZodString>;
    note: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    amount: number;
    kind: "SALE_OFFSPRING_MANUAL";
    quantity?: number | undefined;
    unitPrice?: number | null | undefined;
    subjectProductId?: string | undefined;
    counterpartyName?: string | undefined;
    note?: string | undefined;
    subjectLabel?: string | undefined;
}, {
    kind: "SALE_OFFSPRING_MANUAL";
    quantity?: number | undefined;
    unitPrice?: unknown;
    amount?: unknown;
    subjectProductId?: string | undefined;
    counterpartyName?: string | undefined;
    note?: string | undefined;
    subjectLabel?: string | undefined;
}>, z.ZodObject<{
    kind: z.ZodLiteral<"MANUAL_INCOME">;
    title: z.ZodString;
    amount: z.ZodEffects<z.ZodNumber, number, unknown>;
    note: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    amount: number;
    kind: "MANUAL_INCOME";
    title: string;
    note?: string | undefined;
}, {
    kind: "MANUAL_INCOME";
    title: string;
    amount?: unknown;
    note?: string | undefined;
}>, z.ZodObject<{
    kind: z.ZodLiteral<"MANUAL_EXPENSE">;
    title: z.ZodString;
    amount: z.ZodEffects<z.ZodNumber, number, unknown>;
    note: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    amount: number;
    kind: "MANUAL_EXPENSE";
    title: string;
    note?: string | undefined;
}, {
    kind: "MANUAL_EXPENSE";
    title: string;
    amount?: unknown;
    note?: string | undefined;
}>]>, {
    amount: number;
    kind: "SALE_TURTLE";
    subjectProductId: string;
    counterpartyName?: string | undefined;
    note?: string | undefined;
} | {
    quantity: number;
    unitPrice: number;
    kind: "SALE_OFFSPRING_BATCH";
    subjectProductId: string;
    saleBatchId: string;
    counterpartyName?: string | undefined;
    note?: string | undefined;
} | {
    amount: number;
    kind: "SALE_OFFSPRING_MANUAL";
    quantity?: number | undefined;
    unitPrice?: number | null | undefined;
    subjectProductId?: string | undefined;
    counterpartyName?: string | undefined;
    note?: string | undefined;
    subjectLabel?: string | undefined;
} | {
    amount: number;
    kind: "MANUAL_INCOME";
    title: string;
    note?: string | undefined;
} | {
    amount: number;
    kind: "MANUAL_EXPENSE";
    title: string;
    note?: string | undefined;
}, {
    kind: "SALE_TURTLE";
    subjectProductId: string;
    amount?: unknown;
    counterpartyName?: string | undefined;
    note?: string | undefined;
} | {
    quantity: number;
    kind: "SALE_OFFSPRING_BATCH";
    subjectProductId: string;
    saleBatchId: string;
    unitPrice?: unknown;
    counterpartyName?: string | undefined;
    note?: string | undefined;
} | {
    kind: "SALE_OFFSPRING_MANUAL";
    quantity?: number | undefined;
    unitPrice?: unknown;
    amount?: unknown;
    subjectProductId?: string | undefined;
    counterpartyName?: string | undefined;
    note?: string | undefined;
    subjectLabel?: string | undefined;
} | {
    kind: "MANUAL_INCOME";
    title: string;
    amount?: unknown;
    note?: string | undefined;
} | {
    kind: "MANUAL_EXPENSE";
    title: string;
    amount?: unknown;
    note?: string | undefined;
}>;
export declare const createGuiquanLedgerEntryResponseSchema: z.ZodObject<{
    entry: z.ZodObject<{
        id: z.ZodString;
        source: z.ZodEnum<["SALE_ALLOCATION", "LEDGER_ENTRY"]>;
        direction: z.ZodEnum<["INCOME", "EXPENSE"]>;
        kind: z.ZodEnum<["SALE_TURTLE", "SALE_OFFSPRING", "MANUAL_INCOME", "MANUAL_EXPENSE"]>;
        title: z.ZodString;
        subjectProductId: z.ZodNullable<z.ZodString>;
        subjectCode: z.ZodNullable<z.ZodString>;
        coverImageUrl: z.ZodNullable<z.ZodString>;
        quantity: z.ZodNullable<z.ZodNumber>;
        unitPrice: z.ZodNullable<z.ZodNumber>;
        amount: z.ZodNullable<z.ZodNumber>;
        counterpartyName: z.ZodNullable<z.ZodString>;
        note: z.ZodNullable<z.ZodString>;
        occurredAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        coverImageUrl: string | null;
        quantity: number | null;
        unitPrice: number | null;
        amount: number | null;
        source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
        direction: "INCOME" | "EXPENSE";
        kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
        title: string;
        subjectProductId: string | null;
        subjectCode: string | null;
        counterpartyName: string | null;
        note: string | null;
        occurredAt: string;
    }, {
        id: string;
        coverImageUrl: string | null;
        quantity: number | null;
        unitPrice: number | null;
        amount: number | null;
        source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
        direction: "INCOME" | "EXPENSE";
        kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
        title: string;
        subjectProductId: string | null;
        subjectCode: string | null;
        counterpartyName: string | null;
        note: string | null;
        occurredAt: string;
    }>;
}, "strip", z.ZodTypeAny, {
    entry: {
        id: string;
        coverImageUrl: string | null;
        quantity: number | null;
        unitPrice: number | null;
        amount: number | null;
        source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
        direction: "INCOME" | "EXPENSE";
        kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
        title: string;
        subjectProductId: string | null;
        subjectCode: string | null;
        counterpartyName: string | null;
        note: string | null;
        occurredAt: string;
    };
}, {
    entry: {
        id: string;
        coverImageUrl: string | null;
        quantity: number | null;
        unitPrice: number | null;
        amount: number | null;
        source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
        direction: "INCOME" | "EXPENSE";
        kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
        title: string;
        subjectProductId: string | null;
        subjectCode: string | null;
        counterpartyName: string | null;
        note: string | null;
        occurredAt: string;
    };
}>;
export declare const guiquanLedgerOverviewResponseSchema: z.ZodObject<{
    summary: z.ZodObject<{
        monthKey: z.ZodString;
        allocationCount: z.ZodNumber;
        soldQuantity: z.ZodNumber;
        realizedRevenue: z.ZodNumber;
        incomeAmount: z.ZodNumber;
        expenseAmount: z.ZodNumber;
        netAmount: z.ZodNumber;
        ledgerEntryCount: z.ZodNumber;
        activeBatchCount: z.ZodNumber;
        remainingQuantity: z.ZodNumber;
        eggsEventCount30d: z.ZodNumber;
        matingsEventCount30d: z.ZodNumber;
        allocationsMissingPriceCount: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        monthKey: string;
        allocationCount: number;
        soldQuantity: number;
        realizedRevenue: number;
        incomeAmount: number;
        expenseAmount: number;
        netAmount: number;
        ledgerEntryCount: number;
        activeBatchCount: number;
        remainingQuantity: number;
        eggsEventCount30d: number;
        matingsEventCount30d: number;
        allocationsMissingPriceCount: number;
    }, {
        monthKey: string;
        allocationCount: number;
        soldQuantity: number;
        realizedRevenue: number;
        incomeAmount: number;
        expenseAmount: number;
        netAmount: number;
        ledgerEntryCount: number;
        activeBatchCount: number;
        remainingQuantity: number;
        eggsEventCount30d: number;
        matingsEventCount30d: number;
        allocationsMissingPriceCount: number;
    }>;
    recentEntries: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        source: z.ZodEnum<["SALE_ALLOCATION", "LEDGER_ENTRY"]>;
        direction: z.ZodEnum<["INCOME", "EXPENSE"]>;
        kind: z.ZodEnum<["SALE_TURTLE", "SALE_OFFSPRING", "MANUAL_INCOME", "MANUAL_EXPENSE"]>;
        title: z.ZodString;
        subjectProductId: z.ZodNullable<z.ZodString>;
        subjectCode: z.ZodNullable<z.ZodString>;
        coverImageUrl: z.ZodNullable<z.ZodString>;
        quantity: z.ZodNullable<z.ZodNumber>;
        unitPrice: z.ZodNullable<z.ZodNumber>;
        amount: z.ZodNullable<z.ZodNumber>;
        counterpartyName: z.ZodNullable<z.ZodString>;
        note: z.ZodNullable<z.ZodString>;
        occurredAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        coverImageUrl: string | null;
        quantity: number | null;
        unitPrice: number | null;
        amount: number | null;
        source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
        direction: "INCOME" | "EXPENSE";
        kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
        title: string;
        subjectProductId: string | null;
        subjectCode: string | null;
        counterpartyName: string | null;
        note: string | null;
        occurredAt: string;
    }, {
        id: string;
        coverImageUrl: string | null;
        quantity: number | null;
        unitPrice: number | null;
        amount: number | null;
        source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
        direction: "INCOME" | "EXPENSE";
        kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
        title: string;
        subjectProductId: string | null;
        subjectCode: string | null;
        counterpartyName: string | null;
        note: string | null;
        occurredAt: string;
    }>, "many">;
    recentAllocations: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        batchNo: z.ZodString;
        femaleProductId: z.ZodString;
        femaleCode: z.ZodString;
        coverImageUrl: z.ZodNullable<z.ZodString>;
        quantity: z.ZodNumber;
        unitPrice: z.ZodNullable<z.ZodNumber>;
        amount: z.ZodNullable<z.ZodNumber>;
        buyerName: z.ZodNullable<z.ZodString>;
        channel: z.ZodNullable<z.ZodString>;
        soldAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        batchNo: string;
        femaleProductId: string;
        femaleCode: string;
        coverImageUrl: string | null;
        quantity: number;
        unitPrice: number | null;
        amount: number | null;
        buyerName: string | null;
        channel: string | null;
        soldAt: string;
    }, {
        id: string;
        batchNo: string;
        femaleProductId: string;
        femaleCode: string;
        coverImageUrl: string | null;
        quantity: number;
        unitPrice: number | null;
        amount: number | null;
        buyerName: string | null;
        channel: string | null;
        soldAt: string;
    }>, "many">;
    activeBatches: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        femaleProductId: z.ZodString;
        batchNo: z.ZodString;
        femaleCode: z.ZodString;
        coverImageUrl: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<["OPEN", "PARTIAL", "SOLD", "CLOSED"]>;
        plannedQuantity: z.ZodNumber;
        soldQuantity: z.ZodNumber;
        remainingQuantity: z.ZodNumber;
        priceLow: z.ZodNullable<z.ZodNumber>;
        priceHigh: z.ZodNullable<z.ZodNumber>;
        eventDateSnapshot: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        status: "OPEN" | "PARTIAL" | "SOLD" | "CLOSED";
        soldQuantity: number;
        remainingQuantity: number;
        id: string;
        batchNo: string;
        femaleProductId: string;
        femaleCode: string;
        coverImageUrl: string | null;
        plannedQuantity: number;
        priceLow: number | null;
        priceHigh: number | null;
        eventDateSnapshot: string;
    }, {
        status: "OPEN" | "PARTIAL" | "SOLD" | "CLOSED";
        soldQuantity: number;
        remainingQuantity: number;
        id: string;
        batchNo: string;
        femaleProductId: string;
        femaleCode: string;
        coverImageUrl: string | null;
        plannedQuantity: number;
        priceLow: number | null;
        priceHigh: number | null;
        eventDateSnapshot: string;
    }>, "many">;
    referenceNote: z.ZodNullable<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    summary: {
        monthKey: string;
        allocationCount: number;
        soldQuantity: number;
        realizedRevenue: number;
        incomeAmount: number;
        expenseAmount: number;
        netAmount: number;
        ledgerEntryCount: number;
        activeBatchCount: number;
        remainingQuantity: number;
        eggsEventCount30d: number;
        matingsEventCount30d: number;
        allocationsMissingPriceCount: number;
    };
    recentEntries: {
        id: string;
        coverImageUrl: string | null;
        quantity: number | null;
        unitPrice: number | null;
        amount: number | null;
        source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
        direction: "INCOME" | "EXPENSE";
        kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
        title: string;
        subjectProductId: string | null;
        subjectCode: string | null;
        counterpartyName: string | null;
        note: string | null;
        occurredAt: string;
    }[];
    recentAllocations: {
        id: string;
        batchNo: string;
        femaleProductId: string;
        femaleCode: string;
        coverImageUrl: string | null;
        quantity: number;
        unitPrice: number | null;
        amount: number | null;
        buyerName: string | null;
        channel: string | null;
        soldAt: string;
    }[];
    activeBatches: {
        status: "OPEN" | "PARTIAL" | "SOLD" | "CLOSED";
        soldQuantity: number;
        remainingQuantity: number;
        id: string;
        batchNo: string;
        femaleProductId: string;
        femaleCode: string;
        coverImageUrl: string | null;
        plannedQuantity: number;
        priceLow: number | null;
        priceHigh: number | null;
        eventDateSnapshot: string;
    }[];
    referenceNote: string | null;
}, {
    summary: {
        monthKey: string;
        allocationCount: number;
        soldQuantity: number;
        realizedRevenue: number;
        incomeAmount: number;
        expenseAmount: number;
        netAmount: number;
        ledgerEntryCount: number;
        activeBatchCount: number;
        remainingQuantity: number;
        eggsEventCount30d: number;
        matingsEventCount30d: number;
        allocationsMissingPriceCount: number;
    };
    recentEntries: {
        id: string;
        coverImageUrl: string | null;
        quantity: number | null;
        unitPrice: number | null;
        amount: number | null;
        source: "SALE_ALLOCATION" | "LEDGER_ENTRY";
        direction: "INCOME" | "EXPENSE";
        kind: "SALE_TURTLE" | "SALE_OFFSPRING" | "MANUAL_INCOME" | "MANUAL_EXPENSE";
        title: string;
        subjectProductId: string | null;
        subjectCode: string | null;
        counterpartyName: string | null;
        note: string | null;
        occurredAt: string;
    }[];
    recentAllocations: {
        id: string;
        batchNo: string;
        femaleProductId: string;
        femaleCode: string;
        coverImageUrl: string | null;
        quantity: number;
        unitPrice: number | null;
        amount: number | null;
        buyerName: string | null;
        channel: string | null;
        soldAt: string;
    }[];
    activeBatches: {
        status: "OPEN" | "PARTIAL" | "SOLD" | "CLOSED";
        soldQuantity: number;
        remainingQuantity: number;
        id: string;
        batchNo: string;
        femaleProductId: string;
        femaleCode: string;
        coverImageUrl: string | null;
        plannedQuantity: number;
        priceLow: number | null;
        priceHigh: number | null;
        eventDateSnapshot: string;
    }[];
    referenceNote: string | null;
}>;
export type GuiquanLedgerMonthKey = z.infer<typeof guiquanLedgerMonthKeySchema>;
export type GuiquanLedgerBatchStatus = z.infer<typeof guiquanLedgerBatchStatusSchema>;
export type GuiquanLedgerEntryDirection = z.infer<typeof guiquanLedgerEntryDirectionSchema>;
export type GuiquanLedgerEntryKind = z.infer<typeof guiquanLedgerEntryKindSchema>;
export type GuiquanLedgerEntrySource = z.infer<typeof guiquanLedgerEntrySourceSchema>;
export type GuiquanLedgerQuickEntryKind = z.infer<typeof guiquanLedgerQuickEntryKindSchema>;
export type GuiquanLedgerSummary = z.infer<typeof guiquanLedgerSummarySchema>;
export type GuiquanLedgerAllocationItem = z.infer<typeof guiquanLedgerAllocationItemSchema>;
export type GuiquanLedgerBatchItem = z.infer<typeof guiquanLedgerBatchItemSchema>;
export type GuiquanLedgerEntryItem = z.infer<typeof guiquanLedgerEntryItemSchema>;
export type CreateGuiquanLedgerEntryRequest = z.infer<typeof createGuiquanLedgerEntryRequestSchema>;
export type CreateGuiquanLedgerEntryResponse = z.infer<typeof createGuiquanLedgerEntryResponseSchema>;
export type GuiquanLedgerOverviewResponse = z.infer<typeof guiquanLedgerOverviewResponseSchema>;
