import { z } from 'zod';
export declare const subscriptionOrderStatusSchema: z.ZodEnum<["PENDING", "PAID", "CANCELLED", "REFUNDED", "EXPIRED"]>;
export declare const subscriptionOrderPaymentProviderSchema: z.ZodEnum<["WECHAT", "ALIPAY"]>;
export declare const subscriptionOrderPaymentChannelSchema: z.ZodEnum<["JSAPI", "MINIAPP", "H5"]>;
export declare const subscriptionOrderFulfillmentModeSchema: z.ZodEnum<["IMMEDIATE", "DEFERRED"]>;
export declare const subscriptionOrderBehaviorEventSchema: z.ZodEnum<["DIALOG_OPEN", "PAY_CLICK", "PAY_CANCEL", "PAY_SUCCESS", "PAY_FAILURE", "PAY_HESITATE"]>;
export declare const subscriptionOrderWechatJsapiParamsSchema: z.ZodObject<{
    appId: z.ZodString;
    timeStamp: z.ZodString;
    nonceStr: z.ZodString;
    package: z.ZodString;
    signType: z.ZodLiteral<"RSA">;
    paySign: z.ZodString;
}, "strip", z.ZodTypeAny, {
    appId: string;
    timeStamp: string;
    nonceStr: string;
    package: string;
    signType: "RSA";
    paySign: string;
}, {
    appId: string;
    timeStamp: string;
    nonceStr: string;
    package: string;
    signType: "RSA";
    paySign: string;
}>;
export declare const subscriptionOrderSchema: z.ZodObject<{
    orderId: z.ZodString;
    orderNo: z.ZodString;
    tenantId: z.ZodString;
    userId: z.ZodString;
    plan: z.ZodEnum<["BASIC", "PRO"]>;
    durationDays: z.ZodUnion<[z.ZodLiteral<30>, z.ZodLiteral<90>, z.ZodLiteral<365>]>;
    listPriceCents: z.ZodNullable<z.ZodNumber>;
    totalAmountCents: z.ZodNumber;
    pricingPayRateBps: z.ZodNullable<z.ZodNumber>;
    pricingStartsAt: z.ZodNullable<z.ZodString>;
    pricingEndsAt: z.ZodNullable<z.ZodString>;
    pricingDiscountStatus: z.ZodEnum<["DISABLED", "SCHEDULED", "ACTIVE", "EXPIRED"]>;
    currency: z.ZodString;
    paymentProvider: z.ZodEnum<["WECHAT", "ALIPAY"]>;
    paymentChannel: z.ZodEnum<["JSAPI", "MINIAPP", "H5"]>;
    paymentId: z.ZodNullable<z.ZodString>;
    paymentPrepayId: z.ZodNullable<z.ZodString>;
    status: z.ZodEnum<["PENDING", "PAID", "CANCELLED", "REFUNDED", "EXPIRED"]>;
    statusReason: z.ZodNullable<z.ZodString>;
    fulfillmentMode: z.ZodEnum<["IMMEDIATE", "DEFERRED"]>;
    effectiveStartsAt: z.ZodString;
    createdAt: z.ZodString;
    paidAt: z.ZodNullable<z.ZodString>;
    cancelledAt: z.ZodNullable<z.ZodString>;
    expiresAt: z.ZodString;
    appliedAt: z.ZodNullable<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
    tenantId: string;
    createdAt: string;
    plan: "BASIC" | "PRO";
    expiresAt: string;
    durationDays: 30 | 90 | 365;
    listPriceCents: number | null;
    orderId: string;
    orderNo: string;
    userId: string;
    totalAmountCents: number;
    pricingPayRateBps: number | null;
    pricingStartsAt: string | null;
    pricingEndsAt: string | null;
    pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
    currency: string;
    paymentProvider: "WECHAT" | "ALIPAY";
    paymentChannel: "JSAPI" | "MINIAPP" | "H5";
    paymentId: string | null;
    paymentPrepayId: string | null;
    statusReason: string | null;
    fulfillmentMode: "IMMEDIATE" | "DEFERRED";
    effectiveStartsAt: string;
    paidAt: string | null;
    cancelledAt: string | null;
    appliedAt: string | null;
}, {
    status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
    tenantId: string;
    createdAt: string;
    plan: "BASIC" | "PRO";
    expiresAt: string;
    durationDays: 30 | 90 | 365;
    listPriceCents: number | null;
    orderId: string;
    orderNo: string;
    userId: string;
    totalAmountCents: number;
    pricingPayRateBps: number | null;
    pricingStartsAt: string | null;
    pricingEndsAt: string | null;
    pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
    currency: string;
    paymentProvider: "WECHAT" | "ALIPAY";
    paymentChannel: "JSAPI" | "MINIAPP" | "H5";
    paymentId: string | null;
    paymentPrepayId: string | null;
    statusReason: string | null;
    fulfillmentMode: "IMMEDIATE" | "DEFERRED";
    effectiveStartsAt: string;
    paidAt: string | null;
    cancelledAt: string | null;
    appliedAt: string | null;
}>;
export declare const createSubscriptionOrderRequestSchema: z.ZodObject<{
    plan: z.ZodEnum<["BASIC", "PRO"]>;
    durationDays: z.ZodUnion<[z.ZodLiteral<30>, z.ZodLiteral<90>, z.ZodLiteral<365>]>;
    paymentChannel: z.ZodDefault<z.ZodEnum<["JSAPI", "MINIAPP", "H5"]>>;
}, "strip", z.ZodTypeAny, {
    plan: "BASIC" | "PRO";
    durationDays: 30 | 90 | 365;
    paymentChannel: "JSAPI" | "MINIAPP" | "H5";
}, {
    plan: "BASIC" | "PRO";
    durationDays: 30 | 90 | 365;
    paymentChannel?: "JSAPI" | "MINIAPP" | "H5" | undefined;
}>;
export declare const createSubscriptionOrderResponseSchema: z.ZodObject<{
    order: z.ZodObject<{
        orderId: z.ZodString;
        orderNo: z.ZodString;
        tenantId: z.ZodString;
        userId: z.ZodString;
        plan: z.ZodEnum<["BASIC", "PRO"]>;
        durationDays: z.ZodUnion<[z.ZodLiteral<30>, z.ZodLiteral<90>, z.ZodLiteral<365>]>;
        listPriceCents: z.ZodNullable<z.ZodNumber>;
        totalAmountCents: z.ZodNumber;
        pricingPayRateBps: z.ZodNullable<z.ZodNumber>;
        pricingStartsAt: z.ZodNullable<z.ZodString>;
        pricingEndsAt: z.ZodNullable<z.ZodString>;
        pricingDiscountStatus: z.ZodEnum<["DISABLED", "SCHEDULED", "ACTIVE", "EXPIRED"]>;
        currency: z.ZodString;
        paymentProvider: z.ZodEnum<["WECHAT", "ALIPAY"]>;
        paymentChannel: z.ZodEnum<["JSAPI", "MINIAPP", "H5"]>;
        paymentId: z.ZodNullable<z.ZodString>;
        paymentPrepayId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<["PENDING", "PAID", "CANCELLED", "REFUNDED", "EXPIRED"]>;
        statusReason: z.ZodNullable<z.ZodString>;
        fulfillmentMode: z.ZodEnum<["IMMEDIATE", "DEFERRED"]>;
        effectiveStartsAt: z.ZodString;
        createdAt: z.ZodString;
        paidAt: z.ZodNullable<z.ZodString>;
        cancelledAt: z.ZodNullable<z.ZodString>;
        expiresAt: z.ZodString;
        appliedAt: z.ZodNullable<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    }, {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    }>;
    jsapiParams: z.ZodObject<{
        appId: z.ZodString;
        timeStamp: z.ZodString;
        nonceStr: z.ZodString;
        package: z.ZodString;
        signType: z.ZodLiteral<"RSA">;
        paySign: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        appId: string;
        timeStamp: string;
        nonceStr: string;
        package: string;
        signType: "RSA";
        paySign: string;
    }, {
        appId: string;
        timeStamp: string;
        nonceStr: string;
        package: string;
        signType: "RSA";
        paySign: string;
    }>;
}, "strip", z.ZodTypeAny, {
    order: {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    };
    jsapiParams: {
        appId: string;
        timeStamp: string;
        nonceStr: string;
        package: string;
        signType: "RSA";
        paySign: string;
    };
}, {
    order: {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    };
    jsapiParams: {
        appId: string;
        timeStamp: string;
        nonceStr: string;
        package: string;
        signType: "RSA";
        paySign: string;
    };
}>;
export declare const getSubscriptionOrderResponseSchema: z.ZodObject<{
    order: z.ZodObject<{
        orderId: z.ZodString;
        orderNo: z.ZodString;
        tenantId: z.ZodString;
        userId: z.ZodString;
        plan: z.ZodEnum<["BASIC", "PRO"]>;
        durationDays: z.ZodUnion<[z.ZodLiteral<30>, z.ZodLiteral<90>, z.ZodLiteral<365>]>;
        listPriceCents: z.ZodNullable<z.ZodNumber>;
        totalAmountCents: z.ZodNumber;
        pricingPayRateBps: z.ZodNullable<z.ZodNumber>;
        pricingStartsAt: z.ZodNullable<z.ZodString>;
        pricingEndsAt: z.ZodNullable<z.ZodString>;
        pricingDiscountStatus: z.ZodEnum<["DISABLED", "SCHEDULED", "ACTIVE", "EXPIRED"]>;
        currency: z.ZodString;
        paymentProvider: z.ZodEnum<["WECHAT", "ALIPAY"]>;
        paymentChannel: z.ZodEnum<["JSAPI", "MINIAPP", "H5"]>;
        paymentId: z.ZodNullable<z.ZodString>;
        paymentPrepayId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<["PENDING", "PAID", "CANCELLED", "REFUNDED", "EXPIRED"]>;
        statusReason: z.ZodNullable<z.ZodString>;
        fulfillmentMode: z.ZodEnum<["IMMEDIATE", "DEFERRED"]>;
        effectiveStartsAt: z.ZodString;
        createdAt: z.ZodString;
        paidAt: z.ZodNullable<z.ZodString>;
        cancelledAt: z.ZodNullable<z.ZodString>;
        expiresAt: z.ZodString;
        appliedAt: z.ZodNullable<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    }, {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    }>;
}, "strip", z.ZodTypeAny, {
    order: {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    };
}, {
    order: {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    };
}>;
export declare const cancelSubscriptionOrderResponseSchema: z.ZodObject<{
    order: z.ZodObject<{
        orderId: z.ZodString;
        orderNo: z.ZodString;
        tenantId: z.ZodString;
        userId: z.ZodString;
        plan: z.ZodEnum<["BASIC", "PRO"]>;
        durationDays: z.ZodUnion<[z.ZodLiteral<30>, z.ZodLiteral<90>, z.ZodLiteral<365>]>;
        listPriceCents: z.ZodNullable<z.ZodNumber>;
        totalAmountCents: z.ZodNumber;
        pricingPayRateBps: z.ZodNullable<z.ZodNumber>;
        pricingStartsAt: z.ZodNullable<z.ZodString>;
        pricingEndsAt: z.ZodNullable<z.ZodString>;
        pricingDiscountStatus: z.ZodEnum<["DISABLED", "SCHEDULED", "ACTIVE", "EXPIRED"]>;
        currency: z.ZodString;
        paymentProvider: z.ZodEnum<["WECHAT", "ALIPAY"]>;
        paymentChannel: z.ZodEnum<["JSAPI", "MINIAPP", "H5"]>;
        paymentId: z.ZodNullable<z.ZodString>;
        paymentPrepayId: z.ZodNullable<z.ZodString>;
        status: z.ZodEnum<["PENDING", "PAID", "CANCELLED", "REFUNDED", "EXPIRED"]>;
        statusReason: z.ZodNullable<z.ZodString>;
        fulfillmentMode: z.ZodEnum<["IMMEDIATE", "DEFERRED"]>;
        effectiveStartsAt: z.ZodString;
        createdAt: z.ZodString;
        paidAt: z.ZodNullable<z.ZodString>;
        cancelledAt: z.ZodNullable<z.ZodString>;
        expiresAt: z.ZodString;
        appliedAt: z.ZodNullable<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    }, {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    }>;
}, "strip", z.ZodTypeAny, {
    order: {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    };
}, {
    order: {
        status: "EXPIRED" | "PENDING" | "PAID" | "CANCELLED" | "REFUNDED";
        tenantId: string;
        createdAt: string;
        plan: "BASIC" | "PRO";
        expiresAt: string;
        durationDays: 30 | 90 | 365;
        listPriceCents: number | null;
        orderId: string;
        orderNo: string;
        userId: string;
        totalAmountCents: number;
        pricingPayRateBps: number | null;
        pricingStartsAt: string | null;
        pricingEndsAt: string | null;
        pricingDiscountStatus: "ACTIVE" | "DISABLED" | "EXPIRED" | "SCHEDULED";
        currency: string;
        paymentProvider: "WECHAT" | "ALIPAY";
        paymentChannel: "JSAPI" | "MINIAPP" | "H5";
        paymentId: string | null;
        paymentPrepayId: string | null;
        statusReason: string | null;
        fulfillmentMode: "IMMEDIATE" | "DEFERRED";
        effectiveStartsAt: string;
        paidAt: string | null;
        cancelledAt: string | null;
        appliedAt: string | null;
    };
}>;
export declare const trackSubscriptionOrderBehaviorRequestSchema: z.ZodObject<{
    event: z.ZodEnum<["DIALOG_OPEN", "PAY_CLICK", "PAY_CANCEL", "PAY_SUCCESS", "PAY_FAILURE", "PAY_HESITATE"]>;
    sourcePath: z.ZodString;
    plan: z.ZodOptional<z.ZodEnum<["BASIC", "PRO"]>>;
    durationDays: z.ZodOptional<z.ZodUnion<[z.ZodLiteral<30>, z.ZodLiteral<90>, z.ZodLiteral<365>]>>;
    orderNo: z.ZodOptional<z.ZodString>;
    entryPoint: z.ZodOptional<z.ZodString>;
    stayDurationMs: z.ZodOptional<z.ZodNumber>;
    reason: z.ZodOptional<z.ZodString>;
    result: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    event: "DIALOG_OPEN" | "PAY_CLICK" | "PAY_CANCEL" | "PAY_SUCCESS" | "PAY_FAILURE" | "PAY_HESITATE";
    sourcePath: string;
    reason?: string | undefined;
    plan?: "BASIC" | "PRO" | undefined;
    durationDays?: 30 | 90 | 365 | undefined;
    orderNo?: string | undefined;
    entryPoint?: string | undefined;
    stayDurationMs?: number | undefined;
    result?: string | undefined;
}, {
    event: "DIALOG_OPEN" | "PAY_CLICK" | "PAY_CANCEL" | "PAY_SUCCESS" | "PAY_FAILURE" | "PAY_HESITATE";
    sourcePath: string;
    reason?: string | undefined;
    plan?: "BASIC" | "PRO" | undefined;
    durationDays?: 30 | 90 | 365 | undefined;
    orderNo?: string | undefined;
    entryPoint?: string | undefined;
    stayDurationMs?: number | undefined;
    result?: string | undefined;
}>;
export declare const trackSubscriptionOrderBehaviorResponseSchema: z.ZodObject<{
    recorded: z.ZodLiteral<true>;
}, "strip", z.ZodTypeAny, {
    recorded: true;
}, {
    recorded: true;
}>;
export type SubscriptionOrderStatus = z.infer<typeof subscriptionOrderStatusSchema>;
export type SubscriptionOrderPaymentProvider = z.infer<typeof subscriptionOrderPaymentProviderSchema>;
export type SubscriptionOrderPaymentChannel = z.infer<typeof subscriptionOrderPaymentChannelSchema>;
export type SubscriptionOrderFulfillmentMode = z.infer<typeof subscriptionOrderFulfillmentModeSchema>;
export type SubscriptionOrderBehaviorEvent = z.infer<typeof subscriptionOrderBehaviorEventSchema>;
export type SubscriptionOrderWechatJsapiParams = z.infer<typeof subscriptionOrderWechatJsapiParamsSchema>;
export type SubscriptionOrder = z.infer<typeof subscriptionOrderSchema>;
export type CreateSubscriptionOrderRequest = z.infer<typeof createSubscriptionOrderRequestSchema>;
export type CreateSubscriptionOrderResponse = z.infer<typeof createSubscriptionOrderResponseSchema>;
export type GetSubscriptionOrderResponse = z.infer<typeof getSubscriptionOrderResponseSchema>;
export type CancelSubscriptionOrderResponse = z.infer<typeof cancelSubscriptionOrderResponseSchema>;
export type TrackSubscriptionOrderBehaviorRequest = z.infer<typeof trackSubscriptionOrderBehaviorRequestSchema>;
export type TrackSubscriptionOrderBehaviorResponse = z.infer<typeof trackSubscriptionOrderBehaviorResponseSchema>;
